config/routes.rb
Rails.application.routes.draw do
	root 'blog_posts#new'
  resources :blog_posts
  resources :blog_comments
  resources :comment_answers
  post 'submit_answer', to: 'comment_answers#submit_answer', as: 'submit_answer'
   # devise_for :users


devise_for :users,
           :controllers  => {
             :registrations => 'user/registrations',
          
           }


   # Rails.application.routes.draw do
   #    devise_for :users, controllers: {
   #      sessions: 'users/sessions'
   #    }
   #  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment_answer.rb
class CommentAnswer < ApplicationRecord
  belongs_to :blog_comment
end

app/controllers/comment_answers_controller.rb
class CommentAnswersController < ApplicationController
	def submit_answer
		byebug
	@comment_ans = CommentAnswer.new(reply: params[:answer],blog_comment_id: params[:blog_comment_id])
     @comment_ans.save
     redirect_to :back
	end
	
	def create
	respond_to do |format|
        format.js{render partial: 'comment_answers/answers'}

	end 
	end
end

app/helpers/comment_answers_helper.rb
module CommentAnswersHelper
end

app/views/comment_answers/_answers.html.erb
<%= form_tag submit_answer_path, remote: true, method: :post, id: "comment_answer" do %>
          <%= text_field_tag :answer, '', placeholder: "Type Answer"%>
          <%= hidden_field_tag :blog_comment_id, params[:blog_comment_id]%>
           <%= button_tag 'Submit', class: 'btn btn-primary',
                           data: { disable_with: "<i class='fa fa-refresh fa-spin'>
      </i> Submitting Changes..."} %>
          <%end%>

app/views/comment_answers/_answers.js.erb
$("#<%=params[:blog_comment_id]%>").html("<%= j(render 'comment_answers/answers.html')%>");